[package]
name = "mastodon-instances"
version = "0.1.0"
authors = ["Jan Vandepitte <Jan.Vandepitte@sirus.be>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hdk = { git = "https://github.com/holochain/holochain-rust" , branch = "master" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust" , branch = "master" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
